/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <rcc_hal.h>
#include "gpio_hal.h"


#define FIXED_LIMIT     1600000U

int main(void) {

	initialize_led();

	turn_on_hse();
	set_APB_AHB_prescaler();

	trun_on_led(GREEN_LED);
	for (int i = 0; i <= FIXED_LIMIT; i++);
	trun_off_led(GREEN_LED);

	change_sysclk(SYSCLK_30MHz);

	trun_on_led(ORANGE_LED);
	for (int i = 0; i <= FIXED_LIMIT; i++);
	trun_off_led(ORANGE_LED);

	change_sysclk(SYSCLK_60MHz);

	trun_on_led(RED_LED);
	for (int i = 0; i <= FIXED_LIMIT; i++);
	trun_off_led(RED_LED);

	change_sysclk(SYSCLK_100MHz);

	trun_on_led(BLUE_LED);
	for (int i = 0; i <= FIXED_LIMIT; i++);
	trun_off_led(BLUE_LED);

	for (;;);
}

