/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "gpio_hal.h"

#define RCC_AHB1ENR_Address	((uint32_t)0x40023830)
#define LED_Pin	Green_Led //Replace with required led output

int main(void)
{
	uint32_t volatile *const p_gpioClkReg = (uint32_t*) RCC_AHB1ENR_Address;
	GPIOx *p_gpioa = (GPIOx*) GPIOA_Base_Address;
	GPIOx *p_gpiod = (GPIOx*) GPIOD_Base_Address;

	//Enable clock for the GPIOA and GPIOD port
	*p_gpioClkReg |= GPIOA_EN;
	*p_gpioClkReg |= GPIOD_EN;

	//Configure the GPIOD port
	//Set user push-button pin as input
	p_gpioa->MODER |= GP_Input_Mode<<User_Button*2; //2 bit positions for each GPIO
	//Set Led pin as output
	p_gpiod->MODER |= GP_Output_Mode<<LED_Pin*2; //2 bit positions for each GPIO

	//Pull user push-button pin and Led pin low
	p_gpioa->PUPDR |= Pull_Down<<User_Button*2;
	p_gpiod->PUPDR |= Pull_Down<<LED_Pin*2;


	//forever loop
	while(1){
		if(p_gpioa->IDR & (1<<User_Button)){//Masking the user push-button pin data from the GPIO IDR
			p_gpiod->ODR |= Led_On<<LED_Pin;}
		else{
			p_gpiod->ODR &= Led_Off<<LED_Pin;}
	}
}
