/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>

#include "syscfg_hal.h"
#include "gpio_hal.h"
#include "interupt_hal.h"

// Global declarations
__IO External_interrupt_x *p_EXTI = (External_interrupt_x*) EXTI_BASE_ADDRESS; //External interrupt register
__IO GPIOx *p_GPIOD = (GPIOx*) GPIOD_Base_Address;		//GPIO portD Register

int main(void) {
	__IO uint32_t *p_RCC_AHB1ENR = (uint32_t*) 0x40023830; //RCC_AHB1ENR Register
	__IO uint32_t *p_RCC_APB2ENR = (uint32_t*) 0x40023844; //RCC_APB2ENR Register

	__IO uint32_t *p_NVIC_ISER0 = (uint32_t*) 0xE000E100; // NVIC Interrupt Set Enable Register

	__IO GPIOx *p_GPIOA = (GPIOx*) GPIOA_Base_Address;   //GPIO portA Register

	__IO SYSCFG *p_SYSCFG = (SYSCFG*) SYSCFG_BASE_ADDRESS; // System configuration register

	*p_RCC_AHB1ENR |= GPIOA_EN;		//Enable clock for GPIO port A register
	*p_RCC_AHB1ENR |= GPIOD_EN;		//Enable clock for GPIO port D register
	*p_RCC_APB2ENR |= SYSCFG_EN;	//Enable clock for System configuration register

	// Blue led - output mode with pull down
	p_GPIOD->MODER |= (GP_OUTPUT_Mode << Blue_Led * BIT_2Pos);
	p_GPIOD->PUPDR |= (Pull_Down << Blue_Led * BIT_2Pos);

	// User button - input mode with pull down
	p_GPIOA->MODER |= (GP_INPUT_Mode << User_Button * BIT_2Pos);
	p_GPIOA->PUPDR |= (Pull_Down << User_Button * BIT_2Pos);

	p_SYSCFG->EXTICR1 &= EXTI_PIN_PA0;	//PA0 will the trigger for EXTI0 interrupt

	p_EXTI->EXTI_IMR |= MASK_PA0;	//MASK PA0 output
	p_EXTI->EXTI_RTSR |= TRIGGER_RISING_EDGE; // Trigger the EXTI0 when there is rising edge
	p_EXTI->EXTI_FTSR &= ~TRIGGER_RISING_EDGE;// Disable the falling edge

	*p_NVIC_ISER0 |= EXTI0_EN; // Enable EXTI0 interrupt

	/* Loop forever */
	for (;;);
}

void EXTI0_IRQHandler(void) {
	if (p_EXTI->EXTI_PR & (1 << 0)) {  // Check if EXTI0 triggered
		p_EXTI->EXTI_PR |= (1 << 0);   // Clear interrupt flag
		p_GPIOD->ODR ^= Led_On<<Blue_Led; // Toggle the blue led state
	}
}
