/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>

#include "rcc_hal.h"
#include "gpio_hal.h"
#include "i2c_hal.h"
#include "lsm303agr_hal.h"

// Function declarations
void GPIO_Initialize(GPIOx*);

int main(void)
{
  I2Cx  *p_i2c1  = (I2Cx*) I2C1_Base_Address;
  GPIOx *p_gpiob = (GPIOx*) GPIOB_Base_Address;
  RCC   *p_rcc   = (RCC*) RCC_Base_Address;

  p_rcc->AHB1ENR |= GPIOB_EN;
  p_rcc->APB1ENR |= I2C1_EN;

  uint8_t raw_data[OFFSET_REG_COUNT - 1];
  int16_t x_mag_data, y_mag_data, z_mag_data;

  // Initialize GPIOB Pin 6 and 9
  GPIO_Initialize(p_gpiob);
  printf("GPIO Initialized\n");
  
  // Initialize I2C1
  I2C_Initialize(p_i2c1);
  printf("I2C Initialized\n");

  // Reset the previous configurations (if any).
  i2c_write_single_reg(p_i2c1,Magnetometer,CFG_REG_A_M_Reg,SOFT_RST);
  printf("Magnetometer sensor reset\n");

  // Write initial configuration - continuous mode at 20HZ with high resolution enabled.
  i2c_write_single_reg(p_i2c1,Magnetometer,CFG_REG_A_M_Reg,(ODR_20HZ | MD_CONTINUOUS_MODE));
  printf("Magnetometer sensor configured\nRaw Magnetometer sensor data:\n");

  while(1){
	  while(!(i2c_read_single_reg(p_i2c1, Magnetometer, STATUS_REG_M_Reg) & XYZ_NEW_DATA_AVAILABLE));
	  i2c_read_multiple_reg(p_i2c1,  Magnetometer, OUTX_L_REG_M_Reg, raw_data, OFFSET_REG_COUNT);
	  x_mag_data = (int16_t)((raw_data[1]<<8)|raw_data[0]);
	  y_mag_data = (int16_t)((raw_data[3]<<8)|raw_data[2]);
	  z_mag_data = (int16_t)((raw_data[5]<<8)|raw_data[4]);
	  printf("x:%4d ,y:%4d ,z:%4d\n\n",x_mag_data,y_mag_data,z_mag_data);
	}
  I2C_Terminate(p_i2c1);
}

void GPIO_Initialize(GPIOx* gpio){
  gpio->MODER   |= (0x2<<6*2 | 0x2<<9*2) ;     // Pin6 and Pin9 AF mode
  gpio->AFRL    |= 0x4<<6*4;                   // pin6 AF4 - I2C1
  gpio->AFRH    |= 0x4<<(9-8)*4;               // pin9 AF4 - I2C1
  gpio->OTYPER  |= (1<<6 | 1<<9);              // Pin6 and Pin9 open drain
  gpio->PUPDR   |= (0x1<<6*2 | 0x1<<9*2);      // Pin6 and Pin9 Pull up
  gpio->OSPEEDR |= (0x3<<6*2 | 0x3<<9*2);      // Pin6 and Pin9 High speed
}
