/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>

#include "rcc_hal.h"
#include "gpio_hal.h"
#include "i2c_hal.h"
#include "lsm303agr_hal.h"

#define TEMP_DATA_RATE ODR_10HZ

void GPIO_Initialize(GPIOx*);

int main(void)
{
	I2Cx  *p_i2c1  = (I2Cx*) I2C1_Base_Address;
	GPIOx *p_gpiob = (GPIOx*) GPIOB_Base_Address;
	RCC   *p_rcc   = (RCC*) RCC_Base_Address;

    p_rcc->AHB1ENR |= GPIOB_EN;
    p_rcc->APB1ENR |= I2C1_EN;

  
    GPIO_Initialize(p_gpiob);
    printf("GPIO Initialized\n");
    I2C_Initialize(p_i2c1);
    printf("I2C Initialized\n");

    i2c_augment_single_reg(p_i2c1,Accelerometer,TEMP_CFG_REG_A_Reg,TEMP_Reg_EN);
    i2c_augment_single_reg(p_i2c1,Accelerometer,CTRL_REG4_A_Reg,BDU_EN);
    i2c_augment_single_reg(p_i2c1,Accelerometer,CTRL_REG1_A_Reg,TEMP_DATA_RATE);
    printf("Temperature sensor configured\n");

    uint8_t data[COUNT_TEMP_Regs-1];

    while(1){
		while(!(i2c_read_single_reg(p_i2c1,Accelerometer,STATUS_REG_AUX_A_Reg)&TEMP_DATA_AVAILABLE));
		i2c_read_multiple_reg(p_i2c1, Accelerometer, OUT_TEMP_L_A_Reg, data, COUNT_TEMP_Regs);
		printf("Current temperature = %d*%c\n",(TEMP_OFFSET + (int8_t) data[1]),'C');
    }
    I2C_Terminate(p_i2c1);
}

void GPIO_Initialize(GPIOx* gpio){

    gpio->MODER   |= (0x2<<6*2 | 0x2<<9*2) ;     // Pin6 and Pin9 AF mode
    gpio->AFRL    |= 0x4<<6*4;                   // pin6 AF4 - I2C1
    gpio->AFRH    |= 0x4<<(9-8)*4;               // pin9 AF4 - I2C1
    gpio->OTYPER  |= (1<<6 | 1<<9);              // Pin6 and Pin9 open drain
    gpio->PUPDR   |= (0x1<<6*2 | 0x1<<9*2);      // Pin6 and Pin9 Pull up
    gpio->OSPEEDR |= (0x3<<6*2 | 0x3<<9*2);      // Pin6 and Pin9 High speed
}


