/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "gpio_hal.h"
#include "usart_hal.h"

int main(void)
{
	// Enable clock for for both USART2 and GPIOA
	volatile uint32_t *p_RCC_AHB1ENR = (uint32_t*) RCC_AHB1ENR_Base_Address; // GPIOA bus
	*p_RCC_AHB1ENR |= GPIOA_EN;

	volatile uint32_t *p_RCC_APB1ENR = (uint32_t*) RCC_APB1ENR_Base_Address; // USART2 bus
	*p_RCC_APB1ENR |= USART2_EN;

	volatile GPIOx *p_gpioa = (GPIOx*) GPIOA_Base_Address;
	p_gpioa->MODER |= ((AF_MODE << USART_RX*BIT_FIELD_2) | (AF_MODE << USART_TX*BIT_FIELD_2));
	p_gpioa->OSPEEDR |= ((HIGH_SPEED << USART_RX*BIT_FIELD_2) | (HIGH_SPEED << USART_TX*BIT_FIELD_2));
	p_gpioa->PUPDR |= ((NO_PUPD << USART_RX*BIT_FIELD_2) | (NO_PUPD << USART_TX*BIT_FIELD_2));
	p_gpioa->AFRL |= ((AF_7 << USART_RX*BIT_FIELD_4) | (AF_7 << USART_TX*BIT_FIELD_4));

	volatile USARTx *p_usart2 = (USARTx*) USART2_Base_Address;
	p_usart2->CR1 |= ENABLE_USART;
	p_usart2->CR1 &= EIGHT_DATA_BIT_ONE_START_BIT;
	p_usart2->CR2 &= ONE_STOP_BIT;
	p_usart2->CR1 &= DISABLE_OVER_SAMPLING;
	p_usart2->BRR =  BAUDRATE_9600;
	p_usart2->CR1 |= ENABLE_TE;

	char data[] = "Hi from STM32";
	int data_length = (sizeof(data)/sizeof(data[0]))-1;
	int i = 0;
	while(i < data_length){
		p_usart2->DR = (char)data[i];
		while(!(p_usart2->SR & TXE_FLAG));
		i++;
	}
	p_usart2->DR = (uint8_t)0xA; // New line char
	while(!(p_usart2->SR & TC_FLAG));
	p_usart2->CR1 &= DISABLE_USART;
    /* Loop forever */
	for(;;);
}
